# dir
alias lsa="ls -a"
alias lsd="ls -d .?*;"
alias rmd="rm -rf"
alias sha1="shasum -a 1"
alias sha256="shasum -a 256"
alias up1="cd .. && pwd"
alias up2="cd ../.. && pwd"
alias cd1="up1"
alias cd2="up2"
# net
alias net-dns="host -a"
alias net-ns="host -t NS"
alias ls-pid="ps -ax | grep"
# git
alias gitt="git add ."
# npm
alias npmi="npm i"
alias npmid="npm i -D"
alias npmip="npm i -P"
alias npml="npm run lint"
alias npmb="npm run build"
alias npmlb="npml && npmb"
alias npmib="npmi && npmb"
alias npms="npm start"
alias npmsd="npm run start:dev"
alias npmisd="npmi && npmsd"
alias npmbs="npmb && npms"
alias npmibs="npmi && npmbs"
alias npmsw="npm run start:watch"
alias npmt="npm t"
alias npmti="npm run test:integration"
alias npmj="npm run jest"
alias npmju="npm run jest:unit"
alias npmjw="npm run jest:unit:watch"
alias npmtl="npm run tslint"
alias npmtls="npm run tslint:specs"
alias npmr="npm run"
alias npmrc="npm run compile"
alias npmrcw="npm run compile:watch"
alias npmrcs="npm run compile:specs"
alias npmtd="npm run docker:testint"
alias npmrs="npm run start:sandbox"
alias redo-npm="rmd node_modules && npmi"
# docker
alias dcu="docker-compose -f docker-compose.yml up"
alias dcd="docker-compose down -v"
alias dcl="docker-compose logs"
alias dcls="docker container list"
alias dkill="docker kill $(docker ps -q)"
alias drmimg="docker rmi $(docker images -q)"
# git
alias gfp="git pull && npm i"
alias gfpb="git pull && npmib"
alias gfpbs="git pull && npmibs"
alias gcm="git commit -m"
# js repl
alias jay="npx -p jay-repl jay"
